version: '2'

services:
  zookeeper-main:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-main:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 112.74.44.117
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper-main
